num1=int(input("Enter number"))
num2=int(input("Enter number"))
print("Add",num1+num2)
print("Sub",num1-num2)
print("Multiplication",num1*num2)
print("Division",num1/num2)
print("Modulus",num1%num2)
print("Exponent",num1**num2)
print("Floor Division",num1//num2)
